### ISSUE TITLE
Flip Axes caused some error in 0.6.1.1

### ISSUE THREAD

**Issue by alt-0191** [Kuuuube/Flip_Axes#1]
[MissingMethodException:Error]	Method not found: 'OpenTabletDriver.InputDeviceTreeList OpenTabletDriver.Driver.get_InputDevices()'.
   at Flip_Axes.Flip_Axes_Base.tryResolveOutputMode()
   at Flip_Axes.Flip_Axes_Base.ToUnit_Screen(Vector2 input)
   at Flip_Axes.Flip_Area_Axes.Filter(Vector2 input)
   at Flip_Axes.Flip_Area_Axes.Consume(IDeviceReport value)
   at OpenTabletDriver.Plugin.Output.OutputMode.Consume(IDeviceReport report) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Plugin\Output\OutputMode.cs:line 113
   at OpenTabletDriver.Plugin.Output.OutputMode.Read(IDeviceReport deviceReport) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Plugin\Output\OutputMode.cs:line 115
   at OpenTabletDriver.InputDeviceTree.HandleReport(Object sender, IDeviceReport report) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver\InputDeviceTree.cs:line 61
   at OpenTabletDriver.Devices.DeviceReader`1.OnReport(T report) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver\Devices\DeviceReader.cs:line 140
   at OpenTabletDriver.Devices.DeviceReader`1.Main() in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver\Devices\DeviceReader.cs:line 111

**Comment by Kuuuube** [comment]
Flip Axes 0.0.2 does not support OTD v0.6.1. Use Flip Axes 0.0.3.

You may need to manually delete the version you currently have installed. The OTD plugins folder is located in one of these places:

Windows: `%localappdata%\OpenTabletDriver`
Linux: `~/.config/OpenTabletDriver` or `/usr/share/OpenTabletDriver`
MacOS: `~/Library/Application Support/OpenTabletDriver`

0.0.3 is already on the plugin repo so you can reinstall from there.
